App\Entity\Tree:
  normalizationContext:
    groups: ['tree:read']
  denormalizationContext:
    groups: ['treeInput:write', 'treeUpdateInput:write']
  operations:
    ApiPlatform\Metadata\GetCollection: ~
    ApiPlatform\Metadata\Get: ~
    ApiPlatform\Metadata\Post:
      input: App\Dto\TreeInput
      processor: App\State\TreeProcessor
    ApiPlatform\Metadata\Patch:
      input: App\Dto\TreeUpdateInput
      processor: App\State\TreeProcessor