api_platform:
    title: Hello API Platform
    version: 1.0.0
    defaults:
        stateless: false
        pagination_enabled: true
        pagination_items_per_page: 10
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
    mapping:
        paths:
            - '%kernel.project_dir%/config/api_resources/resources'
    
