App\Dto\ForgotPasswordInput:
  attributes:
    email:
      groups: ['password:forgot:write']

App\Dto\ResetPasswordInput:
  attributes:
    token:
      groups: ['password:reset:write']
    newPassword:
      groups: ['password:reset:write']
