App\Dto\TreeInput:
    attributes:
        scientificName: 
            groups: ['treeInput:write']
        description: 
            groups: ['treeInput:write']
        lifespanMin: 
            groups: ['treeInput:write']
        lifespanMax: 
            groups: ['treeInput:write']
        heightMin: 
            groups: ['treeInput:write']
        heightMax: 
            groups: ['treeInput:write']
        familyName: 
            groups: ['treeInput:write']
        genus: 
            groups: ['treeInput:write']
        species: 
            groups: ['treeInput:write']
        growthRate: 
            groups: ['treeInput:write']
        status: 
            groups: ['treeInput:write']
        temperatureRange:
            groups: ['treeInput:write']
        rainfallRequirement:
            groups: ['treeInput:write']
        waterRequirement:
            groups: ['treeInput:write']
        humidity:
            groups: ['treeInput:write']
        altitudeRange:
            groups: ['treeInput:write']
        sandySoil:
            groups: ['treeInput:write']
        claySoil:
            groups: ['treeInput:write']
        loamySoil:
            groups: ['treeInput:write']
        soilPh:
            groups: ['treeInput:write']
        leafType:
            groups: ['treeInput:write']
        floweringSeason:
            groups: ['treeInput:write']
        harvestTime:
            groups: ['treeInput:write']
        productionPerTree:
            groups: ['treeInput:write']
        seedTreatment:
            groups: ['treeInput:write']
        nurseryMethod:
            groups: ['treeInput:write']
        plantingDistance:
            groups: ['treeInput:write']
        fertilizerSchedule:
            groups: ['treeInput:write']
        irrigationSchedule:
            groups: ['treeInput:write']
        pruningGuide:
            groups: ['treeInput:write']
        commonDiseases:
            groups: ['treeInput:write']
        commonInsects:
            groups: ['treeInput:write']
        symptoms:
            groups: ['treeInput:write']
        treatment:
            groups: ['treeInput:write']
        localNames: 
            groups: ['treeInput:write']
        images: 
            groups: ['treeInput:write']
        uses: 
            groups: ['treeInput:write']
        categories: 
            groups: ['treeInput:write']