services:
    Symfony\Component\Serializer\Normalizer\ObjectNormalizer: ~
    Symfony\Component\Serializer\Normalizer\ArrayDenormalizer: ~
    Symfony\Component\Serializer\Normalizer\DateTimeNormalizer: ~
    # auto-register services in this bundle
    Mahadev\UtilityBundle\:
        resource: "../../*"
        exclude: "../../{DependencyInjection,Entity,Tests}"

    _defaults:
        autowire: true
        autoconfigure: true


    # Commands auto-registration
    # Mahadev\UtilityBundle\Command\:
    #     resource: "%kernel.project_dir%/bundles/Mahadev/UtilityBundle/Command"
    #     tags: ["console.command"]
